world:
  height: 40
  width: 40
  step_time: 0.1
  sample_time: 0.1
  offset: [0, 0]

robot:
  kinematics: {name: 'diff'}
  shape: {name: 'circle', radius: 0.2}
  state: [0, 0, 0]
  sensors:
    - type: 'lidar2d'
      range_min: 0.2
      range_max: 10
      angle_range: 6.2831853 # 2*pi
      number: 5760
      noise: False

obstacle:
  # Left
  - number: 5
    distribution:
      name: 'random'
      range_low: [-8, -8, 0]
      range_high: [-2, 8, 6.28]
    shape:
      # 随机圆（基准半径 0.5，实际会在附近随机变化）
      - {name: 'circle', radius: 0.5, random_shape: True}
      # 随机多边形（尺寸和形状都随机）
      - {name: 'polygon',
         random_shape: true,
         avg_radius_range: [0.3, 0.8],
         irregularity_range: [0, 0.4],
         spikeyness_range: [0, 0.4],
         num_vertices_range: [4, 6]}
    color: 'k'

  # Right
  - number: 5
    distribution:
      name: 'random'
      range_low: [2, -8, 0]
      range_high: [8, 8, 6.28]
    shape:
      # 随机圆（基准半径 0.5，实际会在附近随机变化）
      - {name: 'circle', radius: 0.5, random_shape: True}
      # 随机多边形（尺寸和形状都随机）
      - {name: 'polygon',
         random_shape: true,
         avg_radius_range: [1.3, 1.8],
         irregularity_range: [0, 0.4],
         spikeyness_range: [0, 0.4],
         num_vertices_range: [4, 6]}
    color: 'k'

  # Top
  - number: 5
    distribution:
      name: 'random'
      range_low: [-2, 2, 0]
      range_high: [2, 8, 6.28]
    shape:
      # 随机圆（基准半径 0.5，实际会在附近随机变化）
      - {name: 'circle', radius: 0.5, random_shape: True}
      # 随机多边形（尺寸和形状都随机）
      - {name: 'polygon',
         random_shape: true,
         avg_radius_range: [1.3, 1.8],
         irregularity_range: [0, 0.4],
         spikeyness_range: [0, 0.4],
         num_vertices_range: [4, 6]}
    color: 'k'

  # Bottom
  - number: 5
    distribution:
      name: 'random'
      range_low: [-2, -8, 0]
      range_high: [2, -2, 6.28]
    shape:
      # 随机圆（基准半径 0.5，实际会在附近随机变化）
      - {name: 'circle', radius: 0.5, random_shape: True}
      # 随机多边形（尺寸和形状都随机）
      - {name: 'polygon',
         random_shape: true,
         avg_radius_range: [1.3, 1.8],
         irregularity_range: [0, 0.4],
         spikeyness_range: [0, 0.4],
         num_vertices_range: [4, 6]}
    color: 'k'
