world:
  height: 40
  width: 40
  step_time: 0.1
  sample_time: 0.1
  offset: [0, 0]

robot:
  kinematics: {name: 'omni'}
  shape: {name: 'circle', radius: 0.2}
  state: [-6.0, -1.0, 0.0]
  goal: [6.0, -1.0, 0.0]
  behavior: {name: 'dash'}
  sensors:
    - type: 'lidar2d'
      range_min: 0.2
      range_max: 15
      angle_range: 6.2831853
      number: 1440
      noise: True
      std: 0.01

obstacle:
  - shape: {name: 'rectangle', width: 2.4, length: 2.4}
    state: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

